<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;1,100;1,300;1,400;1,700&display=swap" rel="stylesheet">
    <link href="../styles/style.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">


    <script src="https://kit.fontawesome.com/486886617b.js" crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg bg-light ">
    <div class="container-fluid">

        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <i class="fa-solid fa-earth-asia"></i>
                Nomad-travel
            </a>
        </div>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Destination
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><h5 class="dropdown-item text-warning" href="#">Europe</h5></li>
                        <li><a class="dropdown-item" href="#">Espagne</a></li>
                        <li><a class="dropdown-item" href="#">Italie</a></li>
                        <li><a class="dropdown-item" href="#">Norvège</a></li>
                        <li><h5 class="dropdown-item text-warning" href="#">Asie</h5></li>
                        <li><a class="dropdown-item" href="travel.php?id=<?= $travel["id_country"] ?>">Thaïlande</a></li>
                        <li><a class="dropdown-item" href="#">Indonésie</a></li>
                        <li><a class="dropdown-item" href="#">Japon</a></li>
                        <li><h5 class="dropdown-item text-warning" href="#">Orient</h5></li>
                        <li><a class="dropdown-item" href="#">Dubaï</a></li>
                        <li><a class="dropdown-item" href="#">Emirat</a></li>
                        <li><a class="dropdown-item" href="#">Oman</a></li>
                        <li><h5 class="dropdown-item text-warning" href="#">Amerique</h5></li>
                        <li><a class="dropdown-item" href="#">Mexique</a></li>
                        <li><a class="dropdown-item" href="#">Colombie</a></li>
                        <li><h5 class="dropdown-item text-warning" href="#">Océanie</h5></li>
                        <li><a class="dropdown-item" href="#">Australie</a></li>
                        <li><a class="dropdown-item" href="#">Nouvelle-Zélande</a></li>
                    </ul>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Où et quand partir?
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="#">Janvier</a></li>
                        <li><a class="dropdown-item" href="#">Février</a></li>
                        <li><a class="dropdown-item" href="#">Mars</a></li>
                        <li><a class="dropdown-item" href="#">Avril</a></li>
                        <li><a class="dropdown-item" href="#">Mai</a></li>
                        <li><a class="dropdown-item" href="#">Juin</a></li>
                        <li><a class="dropdown-item" href="#">Juillet</a></li>
                        <li><a class="dropdown-item" href="#">Août</a></li>
                        <li><a class="dropdown-item" href="#">Septembre</a></li>
                        <li><a class="dropdown-item" href="#">Octobre</a></li>
                        <li><a class="dropdown-item" href="#">Novembre</a></li>
                        <li><a class="dropdown-item" href="#">Décembre</a></li>
                    </ul>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Idées de voyage
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="travel.php?id=<?= $idCategory["id_category"][3] ?>">Détente et bien-être</a></li>
                        <li><a class="dropdown-item" href="#">Nature</a></li>
                        <li><a class="dropdown-item" href="#">Culture et patrimoine</a></li>
                        <li><a class="dropdown-item" href="#">Gastronomie</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Qui sommes nous?</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">Demander un devis</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
<?php include 'templates/'.$template.'.phtml'?>
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section
            class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
    >
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
            <span>Get connected with us on social networks:</span>
        </div>
        <!-- Left -->

        <!-- Right -->
        <div>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-facebook-f"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-google"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-instagram"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-linkedin"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-github"></i>
            </a>
        </div>
        <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        <i class="fas fa-gem me-3"></i>Nomad-Travel
                    </h6>
                    <p>
                        Nous créons ensemble votre voyage.
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Products
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Angular</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">React</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Vue</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Laravel</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Useful links
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Pricing</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Settings</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Orders</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Help</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Contact
                    </h6>
                    <p><i class="fas fa-home me-3"></i> Aix-en-Provence, 13100, FR</p>
                    <p>
                        <i class="fas fa-envelope me-3"></i>
                        glmdonizetti@gmail.com
                    </p>
                    <p><i class="fas fa-phone me-3"></i> + 33 767 886 349</p>
                    <p><i class="fas fa-print me-3"></i> + 33 234 567 89</p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2022 Copyright:
        <a class="text-reset fw-bold" href="https://numeridev.com/">numeridev.com</a>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->
</body>
</html>